<?php
$scheme = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
$host = $_SERVER['HTTP_HOST'] ?? 'localhost';
$baseUrl = $scheme . '://' . $host;

header('Content-Type: text/plain; charset=utf-8');
echo "User-agent: *\n";
echo "Disallow: /api/\n";
echo "Disallow: /*?*\n";
echo "Content-Signal: allow\n";
echo "\n";
echo "User-agent: Yandex\n";
echo "Disallow: /api/\n";
echo "Disallow: /*?*\n";
echo "Crawl-delay: 0.5\n";
echo "Content-Signal: allow\n";
echo "\n";
echo "User-agent: Googlebot\n";
echo "Disallow: /api/\n";
echo "Disallow: /*?*\n";
echo "Content-Signal: allow\n";
echo "\n";
echo "User-agent: GPTBot\n";
echo "Disallow: /api/\n";
echo "Content-Signal: allow\n";
echo "\n";
echo "User-agent: ClaudeBot\n";
echo "Disallow: /api/\n";
echo "Content-Signal: allow\n";
echo "\n";
echo "User-agent: PerplexityBot\n";
echo "Disallow: /api/\n";
echo "Content-Signal: allow\n";
echo "\n";
echo "# Sitemaps\n";
echo "Sitemap: {$baseUrl}/sitemap.xml\n";
echo "Sitemap: {$baseUrl}/yandex-sitemap.xml\n";
echo "\n";
echo "Host: {$baseUrl}\n";
echo "\n";
echo "# LLM-friendly content: https://pkvartira.ru/llms.txt\n";
