<?php
$scheme = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
$host = $_SERVER['HTTP_HOST'] ?? 'localhost';
$baseUrl = $scheme . '://' . $host;

echo "User-agent: *\n";
echo "Disallow: /api/\n";
echo "Disallow: /*?*\n";
echo "Content-Signal: allow\n";
echo "\n";
echo "User-agent: Yandex\n";
echo "Disallow: /api/\n";
echo "Disallow: /*?*\n";
echo "Crawl-delay: 0.8\n";
echo "Content-Signal: allow\n";
echo "\n";
echo "User-agent: Googlebot\n";
echo "Disallow: /api/\n";
echo "Disallow: /*?*\n";
echo "Content-Signal: allow\n";
echo "\n";
echo "User-agent: GPTBot\n";
echo "Disallow: /api/\n";
echo "Content-Signal: allow\n";
echo "\n";
echo "User-agent: ClaudeBot\n";
echo "Disallow: /api/\n";
echo "Content-Signal: allow\n";
echo "\n";
echo "User-agent: PerplexityBot\n";
echo "Disallow: /api/\n";
echo "Content-Signal: allow\n";
echo "\n";
echo "# Sitemaps\n";
echo "Sitemap: {$baseUrl}/sitemap.xml\n";
echo "\n";
echo "Host: {$baseUrl}\n";
echo "\n";
echo "LLM-friendly content: https://{$baseUrl}/llms-full.txt\n";